name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  releaseAMW:
    name: Release - Android, Mac, Web
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Permission to Execute Gradle and scripts
        run: |
          chmod +x gradlew
          chmod +x buildApps.sh

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: ./buildApps.sh

      - name: Create Release on GitHub
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.versionName }}
          release_name: v${{ github.event.inputs.versionName }}
          draft: true
          prerelease: false

      - name: Attach Android App 🚀
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: distributions/chakt-android.apk
          asset_name: chakt-android.apk
          asset_content_type: application/apk

      - name: Attach MacOS App 🚀
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: distributions/chakt-macos-x64.jar
          asset_name: chakt-macos-x64.jar
          asset_content_type: application/jar

      - name: Publish Web app 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: distributions/chakt-web

  releaseLinux:
    name: Release - Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Permission to Execute Gradle and scripts
        run: |
          chmod +x gradlew
          chmod +x buildLinux.sh

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: ./buildLinux.sh

      - name: Attach Linux App 🚀
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: distributions/chakt-linux-amd64.jar
          asset_name: chakt-linux-amd64.jar
          asset_content_type: application/jar

  releaseWindows:
    name: Release - Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: .\buildWin.ps1

      - name: Attach Windows App 🚀
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: distributions/chakt-windows-x64.jar
          asset_name: chakt-windows-x64.jar
          asset_content_type: application/jar
