name: Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  releaseAMW:
    name: Release - Android, Mac, Web
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Permission to Execute Gradle and scripts
        run: |
          chmod +x gradlew
          chmod +x buildApps.sh

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Apps for Android, MacOS and Web
        run: ./buildApps.sh

      - name: Attach Android App 🚀
        uses: softprops/action-gh-release@v1
        with:
          files: distributions/chakt-android.apk

      - name: Attach MacOS App 🚀
        uses: softprops/action-gh-release@v1
        with:
          files: distributions/chakt-macos-x64.jar

      - name: Publish Web app 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: distributions/chakt-web

  releaseLinux:
    name: Release - Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Permission to Execute Gradle and scripts
        run: |
          chmod +x gradlew
          chmod +x buildLinux.sh

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: ./buildLinux.sh

      - name: Attach Linux App 🚀
        uses: softprops/action-gh-release@v1
        with:
          files: distributions/chakt-linux-x64.jar

  releaseWindows:
    name: Release - Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build App
        run: .\buildWin.ps1

      - name: Attach Windows App 🚀
        uses: softprops/action-gh-release@v1
        with:
          files: distributions/chakt-windows-x64.jar